services:
  - type: web
    name: nextjs-fullstack
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run
    branch: dev
    rootDir: .
    autoDeploy: true
