[build]
  command = "npm run build"
  publish = "out"

[build.environment]
  NODE_VERSION = "20"

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"

# SPA routing fallback for subpath
[[redirects]]
  from = "/www.damithmendis.com/*"
  to = "/www.damithmendis.com/index.html"
  status = 200
